"""baseline

Revision ID: 467db6759c2c
Revises:
Create Date: 2026-07-18 15:28:59.482212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.db.types


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=True),
    sa.Column('before_state', core.db.types.JsonType(), nullable=True),
    sa.Column('after_state', core.db.types.JsonType(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_created', 'audit_log', ['created_at'], unique=False)
    op.create_table('book_cash',
    sa.Column('book_id', sa.String(length=32), nullable=False),
    sa.Column('cash_usd', core.db.types.Money(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('book_id', name=op.f('pk_book_cash'))
    )
    op.create_table('cash_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.String(length=32), nullable=False),
    sa.Column('amount_usd', core.db.types.Money(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('posted_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('posted_by_username', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_events'))
    )
    op.create_table('doctrine_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distillation_run_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['distillation_run_id'], ['runs.id'], name=op.f('fk_doctrine_versions_distillation_run_id_runs'), use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doctrine_versions')),
    sa.UniqueConstraint('commit_sha', name=op.f('uq_doctrine_versions_commit_sha'))
    )
    op.create_index('ux_doctrine_current', 'doctrine_versions', ['is_current'], unique=True, postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    op.create_table('houses',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('assignable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('meta', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('harness_type', sa.String(length=32), nullable=True),
    sa.Column('config_digest', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('NOT (assignable AND meta)', name=op.f('ck_houses_ck_houses_meta_not_assignable')),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_houses'))
    )
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('route', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('response', core.db.types.JsonType(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys'))
    )
    op.create_table('mm_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ref_type', sa.String(length=24), nullable=False),
    sa.Column('ref_id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('post_id', sa.String(length=64), nullable=False),
    sa.Column('root_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mm_posts')),
    sa.UniqueConstraint('ref_type', 'ref_id', name='uq_mm_posts_ref')
    )
    op.create_table('news_articles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('normalised_url', sa.String(length=2048), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('cluster_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tickers', core.db.types.JsonType(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scores', core.db.types.JsonType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news_articles')),
    sa.UniqueConstraint('url', name=op.f('uq_news_articles_url'))
    )
    op.create_index('ix_news_content_hash', 'news_articles', ['content_hash'], unique=False)
    op.create_index('ix_news_normalised_url', 'news_articles', ['normalised_url'], unique=False)
    op.create_index('ix_news_published', 'news_articles', ['published_at'], unique=False)
    op.create_table('pending_trade_confirmations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=False),
    sa.Column('confirmation_post_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('channel_id', sa.String(length=128), nullable=True),
    sa.Column('trade_json', core.db.types.JsonType(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pending_trade_confirmations')),
    sa.UniqueConstraint('source_ref', name=op.f('uq_pending_trade_confirmations_source_ref'))
    )
    op.create_index('ix_trade_confirmations_status_expires', 'pending_trade_confirmations', ['status', 'expires_at'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book', sa.String(length=32), nullable=False),
    sa.Column('total_nav_usd', core.db.types.Money(), nullable=True),
    sa.Column('positions_json', core.db.types.JsonType(), nullable=True),
    sa.Column('var_results', core.db.types.JsonType(), nullable=True),
    sa.Column('portfolio_beta', core.db.types.Prob(), nullable=True),
    sa.Column('benchmark_correlation', core.db.types.Prob(), nullable=True),
    sa.Column('herfindahl_index', core.db.types.Prob(), nullable=True),
    sa.Column('top1_weight', core.db.types.Prob(), nullable=True),
    sa.Column('top5_weight', core.db.types.Prob(), nullable=True),
    sa.Column('limit_breaches', core.db.types.JsonType(), nullable=True),
    sa.Column('sizing_recommendations', core.db.types.JsonType(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots'))
    )
    op.create_index('ix_portfolio_book_snapshot', 'portfolio_snapshots', ['book', 'snapshot_at'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('net_quantity', sa.Numeric(precision=20, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_cost', core.db.types.Price(), nullable=True),
    sa.Column('book_id', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('last_trade_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('ticker', 'book_id', name='uq_positions_ticker_book')
    )
    op.create_table('price_pins',
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('trading_date', sa.Date(), nullable=False),
    sa.Column('value', core.db.types.Price(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('exchange', 'ticker', 'trading_date', name=op.f('pk_price_pins'))
    )
    op.create_table('risk_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book', sa.String(length=32), nullable=False),
    sa.Column('max_position_pct', core.db.types.Prob(), nullable=True),
    sa.Column('stop_loss_pct', core.db.types.Prob(), nullable=True),
    sa.Column('var_confidence', core.db.types.Prob(), nullable=True),
    sa.Column('var_limit_pct', core.db.types.Prob(), nullable=True),
    sa.Column('rebalance_threshold_pct', core.db.types.Prob(), nullable=True),
    sa.Column('max_sector_pct', core.db.types.Prob(), nullable=True),
    sa.Column('sizing_method', sa.String(length=32), nullable=True),
    sa.Column('kelly_fraction', core.db.types.Prob(), nullable=True),
    sa.Column('max_positions', sa.Integer(), nullable=True),
    sa.Column('historical_lookback_days', sa.Integer(), nullable=True),
    sa.Column('parametric_window_days', sa.Integer(), nullable=True),
    sa.Column('parametric_ewma_lambda', core.db.types.Prob(), nullable=True),
    sa.Column('mc_covariance_window_days', sa.Integer(), nullable=True),
    sa.Column('mc_distribution', sa.String(length=16), nullable=True),
    sa.Column('mc_t_dof', sa.Integer(), nullable=True),
    sa.Column('target_weights', core.db.types.JsonType(), nullable=True),
    sa.Column('scenario_shocks', core.db.types.JsonType(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_configs')),
    sa.UniqueConstraint('book', name=op.f('uq_risk_configs_book'))
    )
    op.create_table('risk_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.String(length=32), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('instruction', core.db.types.JsonType(), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_via_post_id', sa.String(length=64), nullable=True),
    sa.Column('post_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_events')),
    sa.UniqueConstraint('book_id', 'ticker', 'event_type', 'snapshot_at', name='uq_risk_event_snapshot')
    )
    op.create_index('ix_risk_events_book_severity_ack', 'risk_events', ['book_id', 'severity', 'acknowledged'], unique=False)
    op.create_index('ix_risk_events_created_at', 'risk_events', ['created_at'], unique=False)
    op.create_table('scheduler_job_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('runs_created', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduler_job_logs'))
    )
    op.create_index('ix_scheduler_job_logs_job_created', 'scheduler_job_logs', ['job_name', 'created_at'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', core.db.types.Price(), nullable=False),
    sa.Column('currency', sa.String(length=8), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('parse_confidence', core.db.types.Prob(), nullable=True),
    sa.Column('book_id', sa.String(length=32), nullable=False),
    sa.Column('posted_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('posted_by_username', sa.String(length=128), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('buy','sell')", name=op.f('ck_trades_ck_trades_direction')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades')),
    sa.UniqueConstraint('source_ref', name=op.f('uq_trades_source_ref'))
    )
    op.create_index('ix_trades_book_traded_at', 'trades', ['book_id', 'traded_at'], unique=False)
    op.create_index('ix_trades_traded_at', 'trades', ['traded_at'], unique=False)
    op.create_table('coverage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('lead_house', sa.String(length=32), nullable=True),
    sa.Column('dossier_slug', sa.String(length=48), nullable=False),
    sa.Column('earnings_calendar_ref', sa.String(length=64), nullable=True),
    sa.Column('exchange_session_ref', sa.String(length=32), nullable=True),
    sa.Column('pm_notes', sa.Text(), nullable=True),
    sa.Column('proposed_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(state IN ('active','watch','decision_pending')) = (lead_house IS NOT NULL) OR state NOT IN ('active','watch','decision_pending')", name=op.f('ck_coverage_ck_coverage_lead_required_when_live')),
    sa.CheckConstraint("state IN ('proposed','initiating','decision_pending','active','watch','rejected','exited','failed')", name=op.f('ck_coverage_ck_coverage_state')),
    sa.ForeignKeyConstraint(['lead_house'], ['houses.key'], name=op.f('fk_coverage_lead_house_houses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverage')),
    sa.UniqueConstraint('dossier_slug', name='uq_coverage_dossier_slug'),
    sa.UniqueConstraint('exchange', 'ticker', name='uq_coverage_exchange_ticker')
    )
    op.create_index('ix_coverage_state', 'coverage', ['state'], unique=False)
    op.create_table('house_budget_days',
    sa.Column('house', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('reserved_usd', core.db.types.Cost(), server_default=sa.text('0'), nullable=False),
    sa.Column('spent_usd', core.db.types.Cost(), server_default=sa.text('0'), nullable=False),
    sa.Column('cap_usd', core.db.types.Cost(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['house'], ['houses.key'], name=op.f('fk_house_budget_days_house_houses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('house', 'day', name=op.f('pk_house_budget_days'))
    )
    op.create_table('house_metric_snapshots',
    sa.Column('house', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('metrics', core.db.types.JsonType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house'], ['houses.key'], name=op.f('fk_house_metric_snapshots_house_houses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('house', 'as_of', 'scope', name=op.f('pk_house_metric_snapshots'))
    )
    op.create_table('coverage_contributors',
    sa.Column('coverage_id', sa.Uuid(), nullable=False),
    sa.Column('house', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_coverage_contributors_coverage_id_coverage'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['house'], ['houses.key'], name=op.f('fk_coverage_contributors_house_houses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('coverage_id', 'house', name=op.f('pk_coverage_contributors'))
    )
    op.create_table('mm_channels',
    sa.Column('coverage_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('channel_name', sa.String(length=64), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_mm_channels_coverage_id_coverage')),
    sa.PrimaryKeyConstraint('coverage_id', name=op.f('pk_mm_channels')),
    sa.UniqueConstraint('channel_id', name=op.f('uq_mm_channels_channel_id')),
    sa.UniqueConstraint('channel_name', name=op.f('uq_mm_channels_channel_name'))
    )
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coverage_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('trigger_ref', sa.String(length=128), nullable=True),
    sa.Column('priority', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('mutates_dossier', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('params', core.db.types.JsonType(), nullable=False),
    sa.Column('doctrine_version_id', sa.Uuid(), nullable=True),
    sa.Column('budget_cap_usd', core.db.types.Cost(), nullable=True),
    sa.Column('cost_usd', core.db.types.Cost(), server_default=sa.text('0'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('pm_decision', sa.String(length=32), nullable=True),
    sa.Column('dossier_commit_before', sa.String(length=40), nullable=True),
    sa.Column('dossier_commit_after', sa.String(length=40), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(coverage_id IS NOT NULL) OR type = 'distillation'", name=op.f('ck_runs_ck_runs_coverage_required')),
    sa.CheckConstraint("status IN ('queued','running','waiting_pm','succeeded','failed','cancelled')", name=op.f('ck_runs_ck_runs_status')),
    sa.CheckConstraint("type IN ('initiation','deep_review','event_analysis','monitor_tick','pm_query','lead_review','distillation')", name=op.f('ck_runs_ck_runs_type')),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_runs_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['doctrine_version_id'], ['doctrine_versions.id'], name=op.f('fk_runs_doctrine_version_id_doctrine_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_index('ix_runs_coverage_created', 'runs', ['coverage_id', 'created_at'], unique=False)
    op.create_index('ix_runs_status_priority', 'runs', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('uq_runs_trigger_ref', 'runs', ['coverage_id', 'type', 'trigger_ref'], unique=True, postgresql_where=sa.text('trigger_ref IS NOT NULL'), sqlite_where=sa.text('trigger_ref IS NOT NULL'))
    op.create_table('coverage_lead_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coverage_id', sa.Uuid(), nullable=False),
    sa.Column('from_house', sa.String(length=32), nullable=True),
    sa.Column('to_house', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_coverage_lead_history_coverage_id_coverage'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['from_house'], ['houses.key'], name=op.f('fk_coverage_lead_history_from_house_houses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_coverage_lead_history_run_id_runs')),
    sa.ForeignKeyConstraint(['to_house'], ['houses.key'], name=op.f('fk_coverage_lead_history_to_house_houses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverage_lead_history'))
    )
    op.create_table('coverage_levels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coverage_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', core.db.types.Price(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('set_by', sa.String(length=16), nullable=False),
    sa.Column('set_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('below','above')", name=op.f('ck_coverage_levels_ck_coverage_levels_direction')),
    sa.CheckConstraint("kind IN ('entry','target','stop','review')", name=op.f('ck_coverage_levels_ck_coverage_levels_kind')),
    sa.CheckConstraint('value > 0', name=op.f('ck_coverage_levels_ck_coverage_levels_value_positive')),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_coverage_levels_coverage_id_coverage'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['set_by_run_id'], ['runs.id'], name=op.f('fk_coverage_levels_set_by_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverage_levels'))
    )
    op.create_index('ix_coverage_levels_active', 'coverage_levels', ['coverage_id', 'active'], unique=False)
    op.create_table('coverage_run_locks',
    sa.Column('coverage_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_coverage_run_locks_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_coverage_run_locks_run_id_runs')),
    sa.PrimaryKeyConstraint('coverage_id', name=op.f('pk_coverage_run_locks')),
    sa.UniqueConstraint('run_id', name=op.f('uq_coverage_run_locks_run_id'))
    )
    op.create_table('coverage_transitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coverage_id', sa.Uuid(), nullable=False),
    sa.Column('from_state', sa.String(length=24), nullable=True),
    sa.Column('to_state', sa.String(length=24), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('cause', sa.String(length=64), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_coverage_transitions_coverage_id_coverage'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_coverage_transitions_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coverage_transitions'))
    )
    op.create_index('ix_coverage_transitions_coverage_created', 'coverage_transitions', ['coverage_id', 'created_at'], unique=False)
    op.create_table('dossier_index',
    sa.Column('coverage_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=48), nullable=False),
    sa.Column('main_commit', sa.String(length=40), nullable=True),
    sa.Column('updated_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('stance', sa.String(length=16), nullable=True),
    sa.Column('conviction', sa.String(length=16), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('target_price', core.db.types.Price(), nullable=True),
    sa.Column('tripwire_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('files', core.db.types.JsonType(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_dossier_index_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['updated_by_run_id'], ['runs.id'], name=op.f('fk_dossier_index_updated_by_run_id_runs')),
    sa.PrimaryKeyConstraint('coverage_id', name=op.f('pk_dossier_index')),
    sa.UniqueConstraint('slug', name=op.f('uq_dossier_index_slug'))
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coverage_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('payload', core.db.types.JsonType(), nullable=False),
    sa.Column('news_article_id', sa.Uuid(), nullable=True),
    sa.Column('detected_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('handled_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=True),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('pm_rating', sa.SmallInteger(), nullable=True),
    sa.Column('pm_rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pm_rated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_events_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['detected_by_run_id'], ['runs.id'], name=op.f('fk_events_detected_by_run_id_runs')),
    sa.ForeignKeyConstraint(['handled_by_run_id'], ['runs.id'], name=op.f('fk_events_handled_by_run_id_runs')),
    sa.ForeignKeyConstraint(['news_article_id'], ['news_articles.id'], name=op.f('fk_events_news_article_id_news_articles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('dedupe_key', name='uq_events_dedupe_key')
    )
    op.create_index('ix_events_coverage_created', 'events', ['coverage_id', 'created_at'], unique=False)
    op.create_index('ix_events_unhandled', 'events', ['action', 'handled_by_run_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('coverage_id', sa.Uuid(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('payload', core.db.types.JsonType(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=128), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_outbox_events_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_outbox_events_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_outbox_events_dedupe_key'))
    )
    op.create_index('ix_outbox_pending', 'outbox_events', ['delivered_at', 'available_at'], unique=False)
    op.create_table('pm_gates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('coverage_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('payload', core.db.types.JsonType(), nullable=False),
    sa.Column('allowed_answers', core.db.types.JsonType(), nullable=False),
    sa.Column('answer', sa.String(length=32), nullable=True),
    sa.Column('answer_notes', sa.Text(), nullable=True),
    sa.Column('answered_by', sa.String(length=64), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_pm_gates_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_pm_gates_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pm_gates')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_pm_gates_idempotency_key'))
    )
    op.create_index('ix_pm_gates_state_created', 'pm_gates', ['state', 'created_at'], unique=False)
    op.create_table('run_stages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('house', sa.String(length=32), nullable=False),
    sa.Column('substrate', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('depends_on_seq', sa.Integer(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('claimed_by', sa.String(length=64), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('workspace_ref', sa.String(length=256), nullable=True),
    sa.Column('transcript_ref', sa.String(length=256), nullable=True),
    sa.Column('artifacts_ref', core.db.types.JsonType(), nullable=True),
    sa.Column('result', core.db.types.JsonType(), nullable=True),
    sa.Column('cost_usd', core.db.types.Cost(), server_default=sa.text('0'), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('wall_time_s', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','succeeded','failed','skipped')", name=op.f('ck_run_stages_ck_run_stages_status')),
    sa.CheckConstraint("substrate IN ('harness','api')", name=op.f('ck_run_stages_ck_run_stages_substrate')),
    sa.ForeignKeyConstraint(['house'], ['houses.key'], name=op.f('fk_run_stages_house_houses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_stages_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_stages')),
    sa.UniqueConstraint('run_id', 'seq', name='uq_run_stages_run_seq')
    )
    op.create_index('ix_run_stages_claimable', 'run_stages', ['status', 'available_at', 'id'], unique=False)
    op.create_index('ix_run_stages_lease', 'run_stages', ['status', 'lease_expires_at'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('stage_id', sa.Uuid(), nullable=True),
    sa.Column('coverage_id', sa.Uuid(), nullable=True),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_artifacts_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_artifacts_run_id_runs')),
    sa.ForeignKeyConstraint(['stage_id'], ['run_stages.id'], name=op.f('fk_artifacts_stage_id_run_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('sha256', 'kind', name='uq_artifacts_sha_kind')
    )
    op.create_index('ix_artifacts_run', 'artifacts', ['run_id'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('correcting_house', sa.String(length=32), nullable=False),
    sa.Column('attributed_stage_id', sa.Uuid(), nullable=True),
    sa.Column('attributed_house', sa.String(length=32), nullable=True),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('was', sa.Text(), nullable=False),
    sa.Column('now_value', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['attributed_stage_id'], ['run_stages.id'], name=op.f('fk_corrections_attributed_stage_id_run_stages')),
    sa.ForeignKeyConstraint(['correcting_house'], ['houses.key'], name=op.f('fk_corrections_correcting_house_houses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_corrections_run_id_runs')),
    sa.ForeignKeyConstraint(['stage_id'], ['run_stages.id'], name=op.f('fk_corrections_stage_id_run_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrections')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_corrections_idempotency_key'))
    )
    op.create_index('ix_corrections_attributed', 'corrections', ['attributed_house', 'created_at'], unique=False)
    op.create_table('disagreements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('house', sa.String(length=32), nullable=False),
    sa.Column('lead_house', sa.String(length=32), nullable=False),
    sa.Column('material', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('lead_position', sa.Text(), nullable=False),
    sa.Column('challenger_position', sa.Text(), nullable=False),
    sa.Column('key_numbers', core.db.types.JsonType(), nullable=True),
    sa.Column('resolves_if', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house'], ['houses.key'], name=op.f('fk_disagreements_house_houses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_house'], ['houses.key'], name=op.f('fk_disagreements_lead_house_houses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_disagreements_run_id_runs')),
    sa.ForeignKeyConstraint(['stage_id'], ['run_stages.id'], name=op.f('fk_disagreements_stage_id_run_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disagreements'))
    )
    op.create_table('dossier_commits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coverage_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('stage_id', sa.Uuid(), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('branch', sa.String(length=64), nullable=False),
    sa.Column('parent_sha', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('files_changed', core.db.types.JsonType(), nullable=True),
    sa.Column('merged_to_main', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_dossier_commits_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_dossier_commits_run_id_runs')),
    sa.ForeignKeyConstraint(['stage_id'], ['run_stages.id'], name=op.f('fk_dossier_commits_stage_id_run_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossier_commits')),
    sa.UniqueConstraint('commit_sha', name='uq_dossier_commits_sha')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coverage_id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('house', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('value', core.db.types.Price(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('stance', sa.String(length=16), nullable=True),
    sa.Column('scenario_label', sa.String(length=32), nullable=True),
    sa.Column('scenario_prob', core.db.types.Prob(), nullable=True),
    sa.Column('scenario_group', sa.Uuid(), nullable=True),
    sa.Column('horizon_date', sa.Date(), nullable=False),
    sa.Column('confidence', core.db.types.Prob(), nullable=True),
    sa.Column('rationale_ref', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('superseded_run_id', sa.Uuid(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realized_price', core.db.types.Price(), nullable=True),
    sa.Column('realized_return', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('error_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('pinned_price', core.db.types.Price(), nullable=True),
    sa.CheckConstraint("kind <> 'target_price' OR (value IS NOT NULL AND currency IS NOT NULL)", name=op.f('ck_predictions_ck_predictions_target_price_requires_value')),
    sa.CheckConstraint("kind IN ('target_price','entry_point','scenario','event_forecast','stance')", name=op.f('ck_predictions_ck_predictions_kind')),
    sa.CheckConstraint("status IN ('open','hit','miss','expired','superseded')", name=op.f('ck_predictions_ck_predictions_status')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_predictions_ck_predictions_confidence')),
    sa.CheckConstraint('scenario_prob IS NULL OR (scenario_prob >= 0 AND scenario_prob <= 1)', name=op.f('ck_predictions_ck_predictions_scenario_prob')),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_predictions_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['house'], ['houses.key'], name=op.f('fk_predictions_house_houses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_predictions_run_id_runs')),
    sa.ForeignKeyConstraint(['stage_id'], ['run_stages.id'], name=op.f('fk_predictions_stage_id_run_stages')),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['predictions.id'], name=op.f('fk_predictions_superseded_by_id_predictions')),
    sa.ForeignKeyConstraint(['superseded_run_id'], ['runs.id'], name=op.f('fk_predictions_superseded_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_predictions_idempotency_key'))
    )
    op.create_index('ix_predictions_coverage_house', 'predictions', ['coverage_id', 'house', 'created_at'], unique=False)
    op.create_index('ix_predictions_open_horizon', 'predictions', ['status', 'horizon_date'], unique=False)
    op.create_table('stage_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('house', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('substrate', sa.String(length=8), nullable=False),
    sa.Column('worker_id', sa.String(length=64), nullable=True),
    sa.Column('transcript_ref', sa.String(length=256), nullable=True),
    sa.Column('result', core.db.types.JsonType(), nullable=True),
    sa.Column('validation_errors', core.db.types.JsonType(), nullable=True),
    sa.Column('cost_usd', core.db.types.Cost(), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_source', sa.String(length=16), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cached_tokens_in', sa.Integer(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('kill_reason', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running','succeeded','failed','killed','timeout')", name=op.f('ck_stage_attempts_ck_stage_attempts_status')),
    sa.ForeignKeyConstraint(['house'], ['houses.key'], name=op.f('fk_stage_attempts_house_houses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stage_id'], ['run_stages.id'], name=op.f('fk_stage_attempts_stage_id_run_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_attempts')),
    sa.UniqueConstraint('stage_id', 'attempt_no', name='uq_stage_attempts_stage_no')
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('stage_id', sa.Uuid(), nullable=True),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('house', sa.String(length=32), nullable=True),
    sa.Column('coverage_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('substrate', sa.String(length=8), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_input_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', core.db.types.Cost(), nullable=True),
    sa.Column('cost_source', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciled_delta_usd', core.db.types.Cost(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['stage_attempts.id'], name=op.f('fk_llm_usage_attempt_id_stage_attempts')),
    sa.ForeignKeyConstraint(['coverage_id'], ['coverage.id'], name=op.f('fk_llm_usage_coverage_id_coverage')),
    sa.ForeignKeyConstraint(['house'], ['houses.key'], name=op.f('fk_llm_usage_house_houses')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_llm_usage_run_id_runs')),
    sa.ForeignKeyConstraint(['stage_id'], ['run_stages.id'], name=op.f('fk_llm_usage_stage_id_run_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index('ix_llm_usage_house_completed', 'llm_usage', ['house', 'completed_at'], unique=False)
    op.create_index('ix_llm_usage_run', 'llm_usage', ['run_id'], unique=False)
    op.create_table('prediction_hits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prediction_id', sa.Uuid(), nullable=False),
    sa.Column('hit_price', core.db.types.Price(), nullable=False),
    sa.Column('hit_on', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_prediction_hits_prediction_id_predictions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_hits')),
    sa.UniqueConstraint('prediction_id', 'hit_on', name='uq_prediction_hits_day')
    )
    # use_alter FKs cannot be emitted inline in create_table (table cycle); add them after.
    op.create_foreign_key(
        "fk_doctrine_versions_distillation_run_id_runs",
        "doctrine_versions", "runs",
        ["distillation_run_id"], ["id"],
        use_alter=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_doctrine_versions_distillation_run_id_runs", "doctrine_versions", type_="foreignkey"
    )
    op.drop_table('prediction_hits')
    op.drop_index('ix_llm_usage_run', table_name='llm_usage')
    op.drop_index('ix_llm_usage_house_completed', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_table('stage_attempts')
    op.drop_index('ix_predictions_open_horizon', table_name='predictions')
    op.drop_index('ix_predictions_coverage_house', table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('dossier_commits')
    op.drop_table('disagreements')
    op.drop_index('ix_corrections_attributed', table_name='corrections')
    op.drop_table('corrections')
    op.drop_index('ix_artifacts_run', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_run_stages_lease', table_name='run_stages')
    op.drop_index('ix_run_stages_claimable', table_name='run_stages')
    op.drop_table('run_stages')
    op.drop_index('ix_pm_gates_state_created', table_name='pm_gates')
    op.drop_table('pm_gates')
    op.drop_index('ix_outbox_pending', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index('ix_events_unhandled', table_name='events')
    op.drop_index('ix_events_coverage_created', table_name='events')
    op.drop_table('events')
    op.drop_table('dossier_index')
    op.drop_index('ix_coverage_transitions_coverage_created', table_name='coverage_transitions')
    op.drop_table('coverage_transitions')
    op.drop_table('coverage_run_locks')
    op.drop_index('ix_coverage_levels_active', table_name='coverage_levels')
    op.drop_table('coverage_levels')
    op.drop_table('coverage_lead_history')
    op.drop_index('uq_runs_trigger_ref', table_name='runs', postgresql_where=sa.text('trigger_ref IS NOT NULL'), sqlite_where=sa.text('trigger_ref IS NOT NULL'))
    op.drop_index('ix_runs_status_priority', table_name='runs')
    op.drop_index('ix_runs_coverage_created', table_name='runs')
    op.drop_table('runs')
    op.drop_table('mm_channels')
    op.drop_table('coverage_contributors')
    op.drop_table('house_metric_snapshots')
    op.drop_table('house_budget_days')
    op.drop_index('ix_coverage_state', table_name='coverage')
    op.drop_table('coverage')
    op.drop_index('ix_trades_traded_at', table_name='trades')
    op.drop_index('ix_trades_book_traded_at', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_scheduler_job_logs_job_created', table_name='scheduler_job_logs')
    op.drop_table('scheduler_job_logs')
    op.drop_index('ix_risk_events_created_at', table_name='risk_events')
    op.drop_index('ix_risk_events_book_severity_ack', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_table('risk_configs')
    op.drop_table('price_pins')
    op.drop_table('positions')
    op.drop_index('ix_portfolio_book_snapshot', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_trade_confirmations_status_expires', table_name='pending_trade_confirmations')
    op.drop_table('pending_trade_confirmations')
    op.drop_index('ix_news_published', table_name='news_articles')
    op.drop_index('ix_news_normalised_url', table_name='news_articles')
    op.drop_index('ix_news_content_hash', table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_table('mm_posts')
    op.drop_table('idempotency_keys')
    op.drop_table('houses')
    op.drop_index('ux_doctrine_current', table_name='doctrine_versions', postgresql_where=sa.text('is_current'), sqlite_where=sa.text('is_current'))
    op.drop_table('doctrine_versions')
    op.drop_table('cash_events')
    op.drop_table('book_cash')
    op.drop_index('ix_audit_log_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
